export type ICON_TYPES =
  | "after effects"
  | "angular"
  | "blender"
  | "cpp"
  | "docker"
  | "electron"
  | "figma"
  | "firebase"
  | "gamemaker"
  | "graphql"
  | "illustrator"
  | "java"
  | "javascript"
  | "keras"
  | "mongodb"
  | "mysql"
  | "nodejs"
  | "opengl"
  | "photoshop"
  | "premiere"
  | "python"
  | "react"
  | "react native"
  | "redis"
  | "substance designer"
  | "substance painter"
  | "tensorflow"
  | "threejs"
  | "typescript"
  | "unity"
  | "unreal engine"
  | "vulkan"
  | "webgl"
  | "xd";
